version: "3"
services:
  api:
    container_name: "api-security-aula"
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:mysql://mysqldb:3306/aula
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: admin
    #volumes:
    #  - ./logs:/app/logs
    #networks:
    #  - backend
    depends_on:
      - mysqldb

  mysqldb:
    container_name: "mysqldb"
    image: "mysql:8.0"
    restart: "always"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "aula"
      MYSQL_USER: "alvaro"
      MYSQL_PASSWORD: "admin"
      MYSQL_ROOT_PASSWORD: "admin"
    volumes:
      - ./mysql:/var/lib/mysql
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    external: false
